version: '3.9'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_PWD}
      MARIADB_DATABASE: ${DB_NAME}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
  migration-tool:
    build: ./migrations
    profiles:
      - tools
   #platform: linux/amd64
    environment:
      MYSQL_PWD: ${MYSQL_PWD}
      DB_NAME: ${DB_NAME}
      MYSQL_CONNECTION_STRING: ${MYSQL_CONNECTION_STRING}
    depends_on:
      - "db"
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    restart: always
    depends_on:
      - "migration-tool"
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    depends_on:
      - "db"
    ports:
      - "3000:3000"
volumes:
  mariadb: